export const ADMIN_MOCKS = [
    {
        key: '1',
        name: 'John Brown',
        age: 32,
        address: 'New York No. 1 Lake Park',
    },
    {
        key: '2',
        name: 'Jim Green',
        age: 42,
        address: 'London No. 1 Lake Park',
    },
    {
        key: '3',
        name: 'Michael White',
        age: 29,
        address: 'Sydney No. 2 Lake Park',
    },
    {
        key: '4',
        name: 'Anna Black',
        age: 35,
        address: 'Paris No. 3 Lake ParkParis No. 3 Lake ParkParis No. 3 Lake ParkParis No. 3 Lake Park',
    },
    {
        key: '5',
        name: 'David Gray',
        age: 46,
        address: 'Berlin No. 1 Lake Park',
    },
    {
        key: '6',
        name: 'Sarah Blue',
        age: 28,
        address: 'Tokyo No. 2 Lake Park',
    },
    {
        key: '7',
        name: 'William Red',
        age: 38,
        address: 'Madrid No. 3 Lake Park',
    },
    {
        key: '8',
        name: 'Jessica Yellow',
        age: 41,
        address: 'Rome No. 4 Lake Park',
    },
    {
        key: '9',
        name: 'Robert Orange',
        age: 33,
        address: 'Toronto No. 1 Lake Park',
    },
    {
        key: '10',
        name: 'Emily Purple',
        age: 39,
        address: 'Amsterdam No. 2 Lake Park',
    },
    {
        key: '11',
        name: 'Daniel Brown',
        age: 27,
        address: 'New York No. 3 Lake Park',
    },
    {
        key: '12',
        name: 'Sophia Pink',
        age: 44,
        address: 'Chicago No. 1 Lake Park',
    },
    {
        key: '13',
        name: 'Lucas Green',
        age: 30,
        address: 'San Francisco No. 2 Lake Park',
    },
    {
        key: '14',
        name: 'Isabella White',
        age: 36,
        address: 'Seoul No. 3 Lake Park',
    },
    {
        key: '15',
        name: 'Mason Black',
        age: 31,
        address: 'Hong Kong No. 4 Lake Park',
    },
    {
        key: '16',
        name: 'Mia Blue',
        age: 45,
        address: 'Vienna No. 1 Lake Park',
    },
    {
        key: '17',
        name: 'Ethan Gray',
        age: 34,
        address: 'Moscow No. 2 Lake Park',
    },
    {
        key: '18',
        name: 'Olivia Red',
        age: 40,
        address: 'Los Angeles No. 3 Lake Park',
    },
    {
        key: '19',
        name: 'Alexander Yellow',
        age: 25,
        address: 'Sydney No. 4 Lake Park',
    },
    {
        key: '20',
        name: 'Amelia Orange',
        age: 50,
        address: 'Paris No. 1 Lake Park',
    },
    {
        key: '21',
        name: 'James Purple',
        age: 43,
        address: 'London No. 2 Lake Park',
    },
    {
        key: '22',
        name: 'Charlotte Brown',
        age: 37,
        address: 'Berlin No. 3 Lake Park',
    },
];
